<template>
    <div class="start-game-screen">
      <h2>Game Room: {{ gameId }}</h2>
  
      <!-- Current Players Section -->
      <div>
        <h3>Current Players</h3>
        <ul>
          <li v-for="player in players" :key="player">{{ player }}</li>
        </ul>
      </div>
  
      <!-- Buttons -->
      <div class="actions">
        <button @click="startGame" :disabled="players.length < 2">
          Start Game
        </button>
        <button @click="deleteGame">Delete Game</button>
        <button @click="leaveGame">Leave Game</button>
      </div>
    </div>
  </template>
  
  <script setup lang="ts">
  import { ref, watch, onMounted, onUnmounted, computed } from 'vue';
  import { useRoute, useRouter } from 'vue-router';
  import { io } from 'socket.io-client';
  import axios from 'axios';
  
  const route = useRoute();
  const router = useRouter();
  
    // Reactive gameId from the route or null if not present
    const gameId = computed(() => {
    const param = route.params.gameId;
    return Array.isArray(param) ? param[0] : param; // Ensure gameId is a string
});
  const players = ref<string[]>([]); // List of players
    const socket = ref<any>(null);

// Function to join a game by gameId
async function joinGame(gameId: string) {
    try {
        const response = await axios.get(`http://localhost:5000/api/game/${gameId}`);
        players.value = response.data.game.players;
        console.log(`Joined game: ${gameId}`);
    } catch (err) {
        if (axios.isAxiosError(err) && err.response?.status === 404) {
            console.error(`Game with ID ${gameId} not found.`);
            alert('Game not found. Please create a new game.');
            router.push('/'); // Redirect to main screen
        } else {
            console.error('Error joining game:', err);
            alert('Failed to join game.');
            router.push('/');
        }
    }
}

function connectSocket() {
    socket.value = io('http://localhost:5000'); // Connect to the socket server

    // Join the game room
    socket.value.emit('joinGame', { gameId: gameId.value, username: localStorage.getItem('username') });

    // Listen for player updates
    socket.value.on('playerJoined', ({ username }: { username: string }) => {
    if (!players.value.includes(username)) {
        players.value.push(username);
    }
    console.log(`${username} joined the game.`);
});


    // Listen for any messages
    socket.value.on('message', (message: string) => {
    console.log(message);
});

socket.value.on('playerLeft', ({ username }: { username: string }) => {
    players.value = players.value.filter((player) => player !== username);
    console.log(`${username} left the game.`); 
});

 // Listen for the gameStarted event
  socket.value.on('gameStarted', () => {
    console.log('Game started');

    // Navigate to the OnlineHandScreen
    router.push(`/online-hand/${gameId.value}`);
  });

    // Handle disconnections
    socket.value.on('disconnect', () => {
        console.log('Disconnected from the server.');
    });
}


// Function to create a new game
async function createGame() {
    try {
        const createResponse = await axios.post(
            `http://localhost:5000/api/game/create`,
            {}, // Send empty payload; gameId will be generated by the backend
            { headers: { Authorization: `Bearer ${localStorage.getItem('token')}` } }
        );
        const newGameId = createResponse.data.game.gameId; // Extract the new gameId
        players.value = createResponse.data.game.players;

        console.log('Game created:', createResponse.data.game);

        socket.value.emit('createGame', { gameId: newGameId, username: localStorage.getItem('username') });

        // Redirect to the new game
        router.push({ path: `/start-game/${newGameId}` });
    } catch (err) {
        console.error('Error creating game:', err);
        alert('Failed to create game.');
        router.push('/'); // Redirect to main screen if creation fails
    }
}

// Main logic for the component
onMounted(() => {
    if (gameId.value) {
        // If gameId is present in the route, attempt to join the game
        joinGame(gameId.value);
    } else {
        // If no gameId, create a new game
        createGame();
    }
    connectSocket(); // Connect to the socket after fetching the game
});

  
async function startGame() {
    try {
        const response = await axios.post(
            `http://localhost:5000/api/game/close/${gameId.value}`,
            {}, // Send empty payload; gameId will be generated by the backend
            { headers: { Authorization: `Bearer ${localStorage.getItem('token')}` } }
        );
      
        // Emit the startGame event
        socket.value.emit('startGame', { gameId: gameId.value });

    } catch (err) {
        console.error('Error starting game:', err);
        alert('Failed to start game.');
    }
}
  
  const deleteGame = async () => {
    try {
      await axios.delete(`http://localhost:5000/api/game/${gameId.value}`, {
        headers: { Authorization: `Bearer ${localStorage.getItem('token')}` },
      });
      router.push('/'); // Redirect to the main screen after deletion
    } catch (err) {
      console.error('Error deleting game:', err);
      alert('Failed to delete game.');
    }
  };

  // Leave game function
  async function leaveGame() {
    try {
        await axios.post(
            `http://localhost:5000/api/game/leave`,
            { gameId: gameId.value },
            { headers: { Authorization: `Bearer ${localStorage.getItem('token')}` } }
        );

        // Emit the leaveGame event to the server
        if (socket.value) {
            socket.value.emit('leaveGame', { gameId: gameId.value, username: localStorage.getItem('username') });
        }

        alert('You have left the game.');
        router.push('/'); // Redirect to the main page after leaving
    } catch (err) {
        console.error('Error leaving game:', err);
        alert('Failed to leave the game.');
    }
}

onUnmounted(() => {
  if (socket.value) {
    socket.value.disconnect();
  }
});

  </script>
  
  <style scoped>
  .start-game-screen {
    text-align: center;
  }
  
  ul {
    list-style: none;
    padding: 0;
  }
  
  li {
    margin: 5px 0;
  }
  
  .actions button {
    margin: 10px;
    padding: 10px 20px;
    font-size: 16px;
  }
  
  button:disabled {
    background-color: #ccc;
    cursor: not-allowed;
  }
  </style>
  